// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCITNcj_KndjHqq6VQWJyUjkn5Twzu5TMg',
    appId: '1:453267379413:web:c716448e3c745d6cbc3e5c',
    messagingSenderId: '453267379413',
    projectId: 'nyoba-auth-buat-prakmobile',
    authDomain: 'nyoba-auth-buat-prakmobile.firebaseapp.com',
    storageBucket: 'nyoba-auth-buat-prakmobile.appspot.com',
    measurementId: 'G-ZNYFTEF5V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAmvN_jjHzj2hr-nMVUCdrbqpy2Z4SFC8',
    appId: '1:453267379413:android:33411f29bbbcea4dbc3e5c',
    messagingSenderId: '453267379413',
    projectId: 'nyoba-auth-buat-prakmobile',
    storageBucket: 'nyoba-auth-buat-prakmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlVKwzDyqdNfVMcbZFbgA9l2bb9s8bh4',
    appId: '1:453267379413:ios:f4d18ac0789a204cbc3e5c',
    messagingSenderId: '453267379413',
    projectId: 'nyoba-auth-buat-prakmobile',
    storageBucket: 'nyoba-auth-buat-prakmobile.appspot.com',
    iosBundleId: 'com.example.nyobakauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlVKwzDyqdNfVMcbZFbgA9l2bb9s8bh4',
    appId: '1:453267379413:ios:9f17d4087f926a7ebc3e5c',
    messagingSenderId: '453267379413',
    projectId: 'nyoba-auth-buat-prakmobile',
    storageBucket: 'nyoba-auth-buat-prakmobile.appspot.com',
    iosBundleId: 'com.example.nyobakauth.RunnerTests',
  );
}
